### ISSUE TITLE
Causes errors in Rails time calculations

### ISSUE THREAD

**Issue by ykessler** [rbur004/vincenty#4]
See https://stackoverflow.com/questions/46800828/storing-time-with-milliseconds-in-rails

**Comment by rbur004** [comment]
Possibly my overriding Float::round, and returning a float rather than an int for round(0).  That code is now gone.

Or could be the introduction of Numeric::to_r or String::to_r, neither of which existed when Vincenty was first written. These too have been removed, leaving to_radians and the alias to_rad. 

Really need to bound this gem in a module, so these changes aren't global.
